#---------------------------------#
#      environment configuration  #
#---------------------------------#

version: 1.0.{build}

# Needed if project name contains underscore
clone_folder: C:\projects\DSCR_FileContent

init:
  - git config --global core.autocrlf input

install:
    - choco install codecov
    - ps: |
        $moduleName = 'DSCR_FileContent'
        Install-PackageProvider -Name NuGet -Force -ErrorAction Stop
        Write-Host 'Installing NuGet PackageProvider'
        Install-Module Pester -Force -SkipPublisherCheck
        $pester =  Get-Module -ListAvailable -Name Pester | sort Version -Descending | select -First 1
        Write-Host -Message "PowerShell version $($PSVersionTable.PSVersion)"
        Write-Host -Message "Pester version $($pester.Version.ToString())"

#---------------------------------#
#      build configuration        #
#---------------------------------#

build: false

#---------------------------------#
#      test configuration         #
#---------------------------------#

test_script:
    - ps: |
        Write-Host -Message "Test Start"
        $testResultsFile = "$env:APPVEYOR_BUILD_FOLDER/TestsResults.xml"
        $result = Invoke-Pester -CodeCoverage $env:APPVEYOR_BUILD_FOLDER\DSCResources\*\*.psm1 -OutputFormat NUnitXml -OutputFile $testResultsFile -PassThru
        Write-Host -Message "Test Finished"
        Write-Host -Message "Uploading test result"
        $wc = New-Object 'System.Net.WebClient'
        $wc.UploadFile("https://ci.appveyor.com/api/testresults/nunit/$($env:APPVEYOR_JOB_ID)", "$env:APPVEYOR_BUILD_FOLDER/TestsResults.xml")
        Export-CodeCovIoJson -CodeCoverage $result.CodeCoverage -RepoRoot $env:APPVEYOR_BUILD_FOLDER -Path coverage.json
        .\codecov.exe -f "$env:APPVEYOR_BUILD_FOLDER/coverage.json"
        if ($result.FailedCount -gt 0) {
            throw "$($result.FailedCount) tests failed."
        }
        if ($result.PassedCount -eq 0) {
            throw "No tests passed."
        }
        Write-Host -Message "Test script end"
