
[ClassVersion("1.0.0.0"), FriendlyName("TextFile")]
class TextFile : OMI_BaseResource
{
    [Write, ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
    [Key] String Path;
    [Write] String Contents;
    [Write, ValueMap{"utf8", "utf8NoBOM", "utf8BOM", "utf32", "unicode", "bigendianunicode", "ascii", "Default"}, Values{"utf8", "utf8NoBOM", "utf8BOM", "utf32", "unicode", "bigendianunicode", "ascii", "Default"}] String Encoding;
    [Write, ValueMap{"CRLF", "LF"}, Values{"CRLF", "LF"}] String NewLine;
};

